# Generated by Django 6.1.1 on 2026-09-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Слово')),
                ('translation', models.CharField(max_length=200, verbose_name='Перевод')),
                ('example', models.TextField(verbose_name='Пример использования')),
                ('language', models.CharField(choices=[('en', 'Английский'), ('de', 'Немецкий'), ('fr', 'Французский'), ('es', 'Испанский'), ('it', 'Итальянский')], max_length=10, verbose_name='Язык')),
                ('image', models.ImageField(blank=True, null=True, upload_to='word_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['word'],
            },
        ),
    ]
